"""
ChArUco board configuration.

These parameters were reverse-engineered from your sample photos by:
  1. Sweeping every OpenCV ArUco dictionary and counting marker detections
     -> DICT_4X4_100 (marker IDs 0-69, i.e. 70 markers) was the clear winner.
  2. Sweeping candidate (squaresX, squaresY) pairs whose marker count
     (floor(squaresX*squaresY/2)) equals 70, and checking which one lets
     OpenCV's CharucoDetector actually interpolate chessboard corners.
  3. Discovering that corner interpolation only succeeds with
     board.setLegacyPattern(True) -- this board was generated by a tool
     (e.g. calib.io) that uses the pre-4.6 OpenCV marker/corner numbering
     convention, not the modern default.

  -> 10 columns x 14 rows, DICT_4X4_100, legacy pattern = True.

IMPORTANT - you must still fill in the two physical measurements below.
Rotation angles (tilt) do NOT depend on these being exactly correct
(the ratio and the aspect of the grid are what matter for rotation),
but camera calibration quality and any *translation/distance* numbers
will be wrong until you measure your actual printed board with calipers
or a ruler and enter the real values in meters.
"""

import cv2

# --- Grid layout (confirmed against your images) ---
SQUARES_X = 10          # number of squares across (columns)
SQUARES_Y = 14           # number of squares down (rows)
LEGACY_PATTERN = True     # required for this board's marker/corner numbering

# --- Dictionary (confirmed against your images) ---
ARUCO_DICT = cv2.aruco.DICT_4X4_100

# --- Physical measurements: MEASURE YOUR PRINTED BOARD AND FILL THESE IN ---
# Units: meters. Measure the full edge length of one black/white square,
# and separately the edge length of one printed marker (the smaller square
# inside each black square).
SQUARE_LENGTH_M = 0.020   # TODO: replace with your measured square size
MARKER_LENGTH_M = 0.015   # TODO: replace with your measured marker size


def build_board():
    """Create the CharucoBoard + CharucoDetector matching your printed board."""
    dictionary = cv2.aruco.getPredefinedDictionary(ARUCO_DICT)
    board = cv2.aruco.CharucoBoard(
        (SQUARES_X, SQUARES_Y),
        SQUARE_LENGTH_M,
        MARKER_LENGTH_M,
        dictionary,
    )
    board.setLegacyPattern(LEGACY_PATTERN)
    detector = cv2.aruco.CharucoDetector(board)
    return board, detector


def autodetect_dictionary(gray_image, min_markers=6):
    """
    Utility: if you ever swap boards and aren't sure of the dictionary,
    run this against a clear, well-lit photo of the board to find the
    dictionary that detects the most markers.
    """
    candidates = [d for d in dir(cv2.aruco) if d.startswith("DICT_4X4")
                  or d.startswith("DICT_5X5") or d.startswith("DICT_6X6")]
    results = []
    params = cv2.aruco.DetectorParameters()
    for name in candidates:
        adict = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, name))
        detector = cv2.aruco.ArucoDetector(adict, params)
        corners, ids, _ = detector.detectMarkers(gray_image)
        n = 0 if ids is None else len(ids)
        if n >= min_markers:
            results.append((name, n))
    results.sort(key=lambda x: -x[1])
    return results
